word_id_array = [
    None,  # Index 0 is unused since IDs start at 1
    "Sandpaper",
    "Oil",
    "Steam",
    "Acid",
    "Gust",
    "Boulder",
    "Drill",
    "Vacation",
    "Fire",
    "Drought",
    "Water",
    "Vacuum",
    "Laser",
    "Life Raft",
    "Bear Trap",
    "Hydraulic Jack",
    "Diamond Cage",
    "Dam",
    "Sunshine",
    "Mutation",
    "Kevlar Vest",
    "Jackhammer",
    "Signal Jammer",
    "Grizzly",
    "Reinforced Steel Door",
    "Bulldozer",
    "Sonic Boom",
    "Robot",
    "Glacier",
    "Love",
    "Fire Blanket",
    "Super Glue",
    "Therapy",
    "Disease",
    "Fire Extinguisher",
    "Satellite",
    "Confidence",
    "Absorption",
    "Neutralizing Agent",
    "Freeze",
    "Encryption",
    "Proof",
    "Molotov Cocktail",
    "Rainstorm",
    "Viral Meme",
    "War",
    "Dynamite",
    "Seismic Dampener",
    "Propaganda",
    "Explosion",
    "Lightning",
    "Evacuation",
    "Flood",
    "Lava",
    "Reforestation",
    "Avalanche",
    "Earthquake",
    "H-bomb",
    "Dragon",
    "Innovation",
    "Hurricane",
    "Tsunami",
    "Persistence",
    "Resilience",
    "Terraforming Device",
    "Anti-Virus Nanocloud",
    "AI Kill Switch",
    "Nanobot Swarm",
    "Reality Resynchronizer",
    "Cataclysm Containment Field",
    "Solar Deflection Array",
    "Planetary Evacuation Fleet",
    "Antimatter Cannon",
    "Planetary Defense Shield",
    "Singularity Stabilizer",
    "Orbital Laser",
    "Time"
]