words_info = {
    "Sandpaper": {"id": 1, "cost": 8},
    "Oil": {"id": 2, "cost": 10},
    "Steam": {"id": 3, "cost": 15},
    "Acid": {"id": 4, "cost": 16},
    "Gust": {"id": 5, "cost": 18},
    "Boulder": {"id": 6, "cost": 20},
    "Drill": {"id": 7, "cost": 20},
    "Vacation": {"id": 8, "cost": 20},
    "Fire": {"id": 9, "cost": 22},
    "Drought": {"id": 10, "cost": 24},
    "Water": {"id": 11, "cost": 25},
    "Vacuum": {"id": 12, "cost": 27},
    "Laser": {"id": 13, "cost": 28},
    "Life Raft": {"id": 14, "cost": 30},
    "Bear Trap": {"id": 15, "cost": 32},
    "Hydraulic Jack": {"id": 16, "cost": 33},
    "Diamond Cage": {"id": 17, "cost": 35},
    "Dam": {"id": 18, "cost": 35},
    "Sunshine": {"id": 19, "cost": 35},
    "Mutation": {"id": 20, "cost": 35},
    "Kevlar Vest": {"id": 21, "cost": 38},
    "Jackhammer": {"id": 22, "cost": 38},
    "Signal Jammer": {"id": 23, "cost": 40},
    "Grizzly": {"id": 24, "cost": 41},
    "Reinforced Steel Door": {"id": 25, "cost": 42},
    "Bulldozer": {"id": 26, "cost": 42},
    "Sonic Boom": {"id": 27, "cost": 45},
    "Robot": {"id": 28, "cost": 45},
    "Glacier": {"id": 29, "cost": 45},
    "Love": {"id": 30, "cost": 45},
    "Fire Blanket": {"id": 31, "cost": 48},
    "Super Glue": {"id": 32, "cost": 48},
    "Therapy": {"id": 33, "cost": 48},
    "Disease": {"id": 34, "cost": 50},
    "Fire Extinguisher": {"id": 35, "cost": 50},
    "Satellite": {"id": 36, "cost": 50},
    "Confidence": {"id": 37, "cost": 50},
    "Absorption": {"id": 38, "cost": 52},
    "Neutralizing Agent": {"id": 39, "cost": 55},
    "Freeze": {"id": 40, "cost": 55},
    "Encryption": {"id": 41, "cost": 55},
    "Proof": {"id": 42, "cost": 55},
    "Molotov Cocktail": {"id": 43, "cost": 58},
    "Rainstorm": {"id": 44, "cost": 58},
    "Viral Meme": {"id": 45, "cost": 58},
    "War": {"id": 46, "cost": 59},
    "Dynamite": {"id": 47, "cost": 60},
    "Seismic Dampener": {"id": 48, "cost": 60},
    "Propaganda": {"id": 49, "cost": 60},
    "Explosion": {"id": 50, "cost": 62},
    "Lightning": {"id": 51, "cost": 65},
    "Evacuation": {"id": 52, "cost": 65},
    "Flood": {"id": 53, "cost": 67},
    "Lava": {"id": 54, "cost": 68},
    "Reforestation": {"id": 55, "cost": 70},
    "Avalanche": {"id": 56, "cost": 72},
    "Earthquake": {"id": 57, "cost": 74},
    "H-bomb": {"id": 58, "cost": 75},
    "Dragon": {"id": 59, "cost": 75},
    "Innovation": {"id": 60, "cost": 75},
    "Hurricane": {"id": 61, "cost": 76},
    "Tsunami": {"id": 62, "cost": 78},
    "Persistence": {"id": 63, "cost": 80},
    "Resilience": {"id": 64, "cost": 85},
    "Terraforming Device": {"id": 65, "cost": 89},
    "Anti-Virus Nanocloud": {"id": 66, "cost": 90},
    "AI Kill Switch": {"id": 67, "cost": 90},
    "Nanobot Swarm": {"id": 68, "cost": 92},
    "Reality Resynchronizer": {"id": 69, "cost": 92},
    "Cataclysm Containment Field": {"id": 70, "cost": 92},
    "Solar Deflection Array": {"id": 71, "cost": 93},
    "Planetary Evacuation Fleet": {"id": 72, "cost": 94},
    "Antimatter Cannon": {"id": 73, "cost": 95},
    "Planetary Defense Shield": {"id": 74, "cost": 96},
    "Singularity Stabilizer": {"id": 75, "cost": 97},
    "Orbital Laser": {"id": 76, "cost": 98},
    "Time": {"id": 77, "cost": 100}
}